### ISSUE TITLE
RoadMap 汇总/收集贴

### ISSUE THREAD

**Issue by pacoxu** [klts-io/community#2]
当前的 RoadMap 可以查看 https://github.com/klts-io/community/blob/main/Roadmap.md

### 2021 Q3

- [x]  KLTS 启动
- [x]  Kubernetes LTS
- [x]  KLTS.io website
- [x]  KLTS UT
- [x]  国内镜像加速

### 2021 Q4

- [x]  lts.1 发布
- [x]  支持 Centos/Ubuntu
- [x]  一键安装
- [ ]  一键升级到 KLTS 版本 🌟🌟🌟

### 2022 Q1-Q4
- [x]  Containerd LTS 🌟🌟🌟
- [x]  Runc LTS 🌟🌟🌟
- [x] v1.10~v1.23 支持

### 2023

- [x] [DCE](https://docs.daocloud.io/) supports  [v1.18.20-dce.1](https://github.com/klts-io/kubernetes-lts/releases/tag/v1.18.20-dce.1)

### 2024
- [x] v1.24-v1.28 支持

### 2025

- [ ]  离线安装 🌟🌟
- [ ]  E2E 测试多操作系统
- [ ]  支持 ARM 🌟🌟
- [ ]  支持麒麟系统 
- [ ]  支持跨版本升级 🌟🌟🌟
- [ ]  升级速度评估 Benchmark 
- [ ]  项目进入 CNCF Sandbox 🌟🌟🌟🌟
- [ ]  支持 Fedora 
- [ ]  支持 Opensuse 
- [ ]  云原生组件和系统性能调优
